### ISSUE TITLE
Update Chivolo README

### ISSUE THREAD

**Issue by georgiakirkpatrick** [georgiakirkpatrick/chivolo#1]
---
name: "Feature request \U0001F680"
about: Suggest an idea
labels: Enhancement

---

### Summary

Add details to README

### Basic example

[README template](https://github.com/georgiakirkpatrick/readme-template).

### Motivation

Having a detailed README file will facilitate collaboration on the Veronaut project and better show off my work to prospective employers and collaborators.

#### Intro

- [x] Review short project description and decide whether to keep it or revise it.

##### Context

> - [x] Bootcamp context.  What was the assignment?
> - [x] Why is representation in media important?

##### Features

- [x] Add to "About The Project" what the Chivolo application does.
- [x] Create a "Features" subsection in "About the Project" with a list of features about the app in general.  
- [x] List features
- [x] Provide short descriptions of each feature
- [x] Include screenshots as needed
- [x] Include information about how database is organized.

##### Built With

- [x] Add to "About The Project" why I used the technologies I used.
- [x] Format technologies as badges as in template.

#### Getting Started
This is an example of how you may give instructions on setting up your project locally.

If you are working on a project that a user needs to install or run locally in a machine like a "POS", you should include the steps required to install your project and also the required dependencies if any.

Provide a step-by-step description of how to get the development environment set and running.

- [x] List all the steps
- [x] Write detailed instructions for each step
- [x] Include screenshots of steps where needed

##### Prerequisites

This is an example of how to list things you need to use the software and how to install them.

- [x] List all things needed to use the software
- [x] For each thing, explain why it is needed
- [x]  For each thing, include links to how to access it

##### Installation

- [x] Write step by step instructions of how to install the app.

#### Usage

Use this space to show useful examples of how a project can be used. Additional screenshots, code examples and demos work well in this space. You may also link to more resources.

Provide instructions and examples so users/contributors can use the project. This will make it easy for them in case they encounter a problem – they will always have a place to reference what is expected.

You can also make use of visual aids by including materials like screenshots to show examples of the running project and also the structure and design principles used in your project.

Also if your project will require authentication like passwords or usernames, this is a good section to include the credentials.

- [ ] Include instructions on how to get authentication info and how to include it in a local version of the app

#### Roadmap

(Below text is from https://mozillascience.github.io/working-open-workshop/roadmapping/)

When you're starting on an open source project, it's important to record what your community (this might just be you at the beginning) decides to work on! A roadmap organizes the tasks that nees to be done on a project around milestones. This helps potential contributors understand the current status of your poject and where it's going next.

A roadmap can also express your vision for the project. Make sure you clearly state why you are implementing certain things to get people excited about joining.

This can be as simple as a collection of issues in your issue tracker, or a detailed timeline complete with milestones. It's up to you to choose what works best for your community!

This section organizes tasks needed to complete your project around milestones, mapping out what you're working on now and where it's going next. This can be as simple as a list of issues in your issue tracker.

- [ ] Add some of the challenges I faced with the app.
- [ ] Add features I hope to implement in the future.  Link to "Issues" as applicable.
- [ ] Pick Milestones
Depending on your project, milestones can vary from development goals to events. Here are some milestones you can use:

>- Project Status Goals
Are you working to implement your MVP (minimum viable product) or a specific feature? Your milestones can be completing a feature or a release.
>examples: Get your project on Collaborate, build an MVP

>- Dates
If you have deadlines or a set time to work on this project, use this as a milestone!

>- Events
If you'll be sprinting or demoing your project at an event, it's helpful to know what you'll need to complete before and during the event.
>examples: Mozilla Science Lab Global Sprint prep work, MozFest sprint tasks

>- Short, Medium & Long Term
When working with volunteers, it can be difficult to set hard deadlines. When unsure, you can use short, medium and long term milestones.

>>- Short term - things you are working on now
>>- Medium term - things contributors can start working on that is not currently being worked on
>>- Long term - you can describe where your project is going here

> - [ ] Write a milestone for each task
> - [ ] Create an issue for each task. Take time to describe the task along with why you are doing this task. This will strengthen the vision for your project and help others get involved.
Tips for issues: Include as much context and help as possible! Add links, mention specific people involved by their username (i.e. @acabunoc). Articulate the problem or idea along with solutions and next steps.

Link to these issues in your Roadmap under each milestone. Congrats! You now have a Roadmap with tasks.

#### Contributing

- [x] Replace "AmazingFeature" with repo name
- [x] Make sure instructions are accurate for Chivolo.

#### License

The most common one is the GPL License which allows other to make modification to your code and use it for commercial purposes. If you need help choosing a license, use check out this link: https://choosealicense.com/

- [ ] Research licenses
- [ ] Implement license 
- [ ] Add a LICENSE.txt file
- [ ] Add license info to README

#### Acknowledgements

- [x] If you worked on the project as a team or an organization, list your collaborators/team members. You should also include links to their GitHub profiles and social media too.
- [x] Also, if you followed tutorials or referenced a certain material that might help the user to build that particular project, include links to those here as well.

#### Lastly

- [x] Update Table of Contents as needed, based on README section updates.
